### ISSUE TITLE
PCB Desgin

### ISSUE THREAD

**Issue by larszi** [tatemazer/brewhob#1]
Hi Tate,
Really nice project and video to go along with it!
Do you plan on publishing the design of the PCB in the future? 
I would really love to see the PCB, some doc about the design!
Thanks for the interesting project!
Best regards!

Lars

**Comment by tatemazer** [comment]
Hi @larszi , thanks for your kind words. I'll be sure to release those files when they're ready, unfortunately they're still early in development.

**Comment by larszi** [comment]
Really nice, to hear I will be looking forward to that!

**Comment by CyB0rgg** [comment]
Hi,
Just acquired s/h GS3 and I am very interested in your mod. Same question as above, almost a year later. Can we please have the PCB ? Unless you are willing to sell the bare / populated board ? I'm game !

Thanks

**Comment by cjattard** [comment]
as an owner of an appartamento myself and a full on tinkerer i would also be interested in either purchasing the board directly, or assembling my own once your schematic is published.

amazing work.

**Comment by tatemazer** [comment]
Hi all, sorry for the delay. As you may have seen, the [brew-by-weight](https://github.com/tatemazer/AcaiaArduinoBLE) device I'm developing  is taking my full bandwidth at the moment. I may return to developing a stable version of the brewhob in the future.
